version: '3.8'

services:
  time-tracker:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped