# Docker Compose configuration for Time Tracker

services:
  time-tracker:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: time-tracker
    ports:
      - "8501:8501"  # Streamlit UI
    volumes:
      - ./app:/app
      - ./data:/app/data
    env_file:
      - ./app/.env
    restart: unless-stopped