# version: '3.8' --the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion

services:
  time-tracker:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./data:/app/data
    env_file:
      - ./app/.env
    restart: unless-stopped