# Docker Compose configuration for Time Tracker

services:
  time-tracker:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: time-tracker
    ports:
      - "8501:8501"  # Streamlit UI
    networks:
      - web
    volumes:
      - ./app:/app
      # - ./data:/app/data
    env_file:
      - ./app/.env
    restart: unless-stopped

networks:
  web:
    external: true
# Define the external network 'web' to be used by the container
# This allows the container to communicate with other services on the same network
# Ensure that the external network 'web' is created before running this docker-compose file