version: '3'

services:
  webapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: time-tracker-webapp
    ports:
      - "8000:8000"  # FastAPI
    networks:
      - web
    volumes:
      - ./app:/app
    env_file:
      - ./app/.env
    restart: unless-stopped
    environment:
      - WATCHFILES_FORCE_POLLING=true  # For hot reload in Docker

networks:
  web:
    external: true
